### ISSUE TITLE
`DBPrimaryKeyField::scaffoldSearchField()` doesn't return anything?

### ISSUE THREAD

**Issue by mlewis-everley** [silverstripe/silverstripe-framework#10809]
https://github.com/silverstripe/silverstripe-framework/blob/fd57f06755d73ae77ecb93a5380e2ba3d56dbe95/src/ORM/FieldType/DBPrimaryKey.php#L61

I am not sure if this is intentional (I cannot see how/why), but this method doesn't return the field it creates.

I am bumping into this issue which trying to scaffold search against a `has_one` relation (by `relation.ID`)

**Comment by johannesx75** [comment]
This has been fixed in the version 6 Branch; https://github.com/silverstripe/silverstripe-framework/blob/6/src/ORM/FieldType/DBPrimaryKey.php#L56

@GuySartorelli does that solve the issue, or do you want to have this back ported to older versions?

**Comment by GuySartorelli** [comment]
@johannesx75 The bug is still present in 5.4 which is still supported for bug fixes. This issue can be closed either when this is resolved in 5.4 or when 5.4 loses support.

**Comment by johannesx75** [comment]
@GuySartorelli ok, I've made a little back port: https://github.com/silverstripe/silverstripe-framework/pull/11856

**Comment by GuySartorelli** [comment]
Cheers. PR merged.
