### ISSUE TITLE
Issue #916 (Inspect current directory for include_path) still not resolved in some set ups

### ISSUE THREAD

**Issue by Juanitou** [silverstripe/silverstripe-framework#3483]
Issue #916 is not resolved yet in all set ups. I have a “multi-sites” one in a shared host with open_basedir enabled, where only one install of SilverStripe is shared between two (or more) sites through symbolic links. Here is the folder schema:
`/home/atelierd/`
`|--- firstdomain/`
`...|--- private_html/`
`......|--- cms/`
`......|--- framework/`
`......|--- [modules]/`
`...|--- public_html/` 
`......|--- assets/`
`......|--- cms/ --> /home/atelierd/firstdomain/private_html/cms` 
`......|--- framework/ --> /home/atelierd/firstdomain/private_html/framework`
`......|--- [modules]/ --> /home/atelierd/firstdomain/private_html/[modules]`
`......|--- mysite/`
`......|--- silverstripe-cache/`
`......|--- themes/`
`|--- seconddomain/`
`...|--- public_html/`
`......|--- assets/`
`......|--- cms/ --> /home/atelierd/firstdomain/private_html/cms` 
`......|--- framework/ --> /home/atelierd/firstdomain/private_html/framework`
`......|--- [modules]/ --> /home/atelierd/firstdomain/private_html/[modules]`
`......|--- mysite/`
`......|--- silverstripe-cache/`
`......|--- themes/`

This work a treat but I’m getting the following **only when visiting pages of the second domain**:
`Warning at home/atelierd/domains/firstdomain.org/private_html/framework/thirdparty/Zend/Loader.php line 198: is_readable(): open_basedir restriction in effect. File(/usr/local/lib/php/Zend/Translate/Adapter/I18nRailsYamlAdapter.php) is not within the allowed path(s): (/home/atelierd/:/tmp:/var/tmp:/usr/local/php5/lib/php). **(http://www.seconddomain.org/)**`

The file exists and is located as expected in:
`home/atelierd/domains/firstdomain.org/private_html/framework/i18n/i18nRailsYamlAdapter.php`

This is a recently updated 3.1.6 install, without custom code.

I would like to help debug it but I don’t know where to start.

Best regards.

**Comment by muskie9** [comment]
Has there been any updates to this? We've recently launched a site with 3.1.13 and are seeing the warning on production. We don't control the hosting environment unfortunately so our options for `php.ini` settings are limited.

**Comment by MrJamesEllis** [comment]
This issue keeps rearing it's ugly head, specifically for me in FPM installs where there is an open_basedir implemented.

I commented here on a possible workaround:
https://github.com/silverstripe/silverstripe-framework/pull/916#issuecomment-151347456

It's confusing about why this happens in the first place. is_readable checks whether the file exists and is readable (http://php.net/manual/en/function.is-readable.php). It should just return FALSE when the path is in the open_basedir settings (as it was) and the file either doesn't exist or is not readable.

Maybe I'm missing something but the solution I found was to explicitly set the include_path to "." as per that linked comment.

Note that in the original comment to this issue the open_basedir contains "/usr/local/php5/lib/php" whereas the error message states "File(/usr/local/lib/php/Zend/Translate/Adapter/I18nRailsYamlAdapter.php) is not within the allowed path(s):"
This is a bit different to the error I get when the path being accessed is in the open_basedir setting.


Separately to this the file name in the error is "I18nRailsYamlAdapter.php" whereas the file on disk is in framework/i18n/i18nRailsYamlAdapter.php - case sensitive systems would trip up on this ? Windows would probably happily say all is OK ?

**Comment by dhensby** [comment]
@mrjamesellis is this something you're prepared to fix and open a PR for?

**Comment by chillu** [comment]
Closing due to lack of feedback (might also be fixed in 4.x since we've completely restructured i18n module inclusion)

**Comment by micschk** [comment]
For anyone stumbling across this bug (still occurs in the 3.x versions); it seems to be caused by Zend libraries being present in a shared location (eg local/lib/php/Zend/etc).

Removing these public/shared folders from your include path seems to fix the issue (FW is self-contained/has a copy of the libraries anyway). 

In your _ss_environment.php:
```php
set_include_path('.');
```
