### ISSUE TITLE
Cannot Deselect Last Item in TreeMultiselectField

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-framework#4240]
When deselecting the last item from a TreeMultiselectField, despite the checkbox becoming unticked, the item remains as the field's value.

**To reproduce:**
1. Create a TreeMultiselectField
2. In the CMS open the drop-down and tick more than one item. Each ticked item appears in the field's value.
3. Untick an item and it is correctly removed from the field's value.
4. Untick the last item.

**What happens:**
Despite being unticked, it's value remains listed in the field.

**What I expect to happen:**
The name of the last item to be removed from the field's value, and the default "(Choose)" text to appear, indicating that no items have been selected.

 ![](http://spdr.me/5vsN+)

**Comment by purplespider** [comment]
Still an issue in 3.2-beta1

**Comment by dhensby** [comment]
#4272 should fix this. It needs to be merged up into 3.2

**Comment by kinglozzer** [comment]
This should’ve been merged up now, @purplespider can you retest if this is still an issue?

**Comment by purplespider** [comment]
Still seeing this issue in 3.1.x-dev. 3.2.x-dev and 3.2.0-beta2, am I missing something?

**Comment by dhensby** [comment]
hey @purplespider great to see you at stripeconEU!

I've had this on my list for a while to look into - is it STILL a problem?

**Comment by purplespider** [comment]
Hi Dan! Ditto!

Yup, I can confirm this still occurs on 3.2.0 (and also checked on 3.2.x-dev).

**Comment by dhensby** [comment]
got a fix for you :)

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4852

**Comment by purplespider** [comment]
:+1:
