### ISSUE TITLE
GridFieldPaginator doesn't accept manually entered page numbers

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-framework#5093]
For some reason (currently a mystery to me why), the `GridFieldPaginator` paginator doesn't allow you to manually enter a specific page number to go to.  

**To reproduce:**
1. Go to a paginated grid field with 3 or more pages.
2. **Important:** Ensure that grid field has a name (not a title) with a space in it.
3. Type in the number 3 and press enter.
4. It refreshes the frame and shows just the first page.

This happens even if you start on page 2 or even on page 3. If you clicked the single arrow or double it works as expected (going to the next page or the last page, respectively). 

**Other symptoms:**
- I did notice that in the network transfer, pressing enter did not include the parameter `action_gridFieldAlterAction?StateID=gf_2bf77aca` (contains the value of `Next` if you click the arrow and `Last` if you clicked the double arrow button)
- The `->handleAction()` method never gets called when you press enter to submit your new selection. 

**Edit:** Modified instructions to ensure you have a grid field with a name that has a space in it (required to reproduce bug successfully).

**Comment by tractorcow** [comment]
Yeah this is a valid bug. Probably needs to be fixed in the frontend JS code? It hasn't worked for as long as I've known about it.

**Comment by tractorcow** [comment]
PR anyone?

**Comment by patricknelson** [comment]
I might be able/willing to throw out a PR if I knew already what on earth was causing it. I don't know/understand the internals of how `GridField` receives/processes information about the proper state (at the moment). That's a mystery to me. Do you happen to know off hand what's causing it? If not, no huge deal.

**Comment by tractorcow** [comment]
It's still a little magic to me as well... I guess debug what's currently happening, then finding the part of GridField.js that's triggering the refresh?

**Comment by patricknelson** [comment]
Well the refresh part I have an intuition is coming from some entwine goodness that was originally built to ... helpfully... submit forms when pressing enter. The issue is that the mechanism by which it does this is by simply registering the `click` event on the first button found on the current form. I could be wrong.

**Comment by patricknelson** [comment]
If that were indeed the case (not at a computer right now and don't wanna look at one) then I'd assume maybe the solution would then be to intervene directly on `keypress` events on that particular field and then `preventDefault` and finally do [whatever it is] that the regular buttons are doing in order to send the extra `action_gridFieldAlterAction` parameter that the gridfield is probably watching in order to refresh/maintain state (assuming that's how it watches for update). Theoretically that's probably the case considering I recall network transfers being exactly the same except for the `currentPage` and that funky field.

**Comment by patricknelson** [comment]
Curious, I just noticed some RC's just came out: Did the fix of this regression have anything to do with the investigation caused by the current ticket? https://github.com/silverstripe/silverstripe-framework/commit/2c1b934ba225101cf02950a461b012463b7b62de

**Comment by dhensby** [comment]
@patricknelson is it now working with that fix?!

**Comment by tractorcow** [comment]
If it worked in 3.2.1 then maybe. Otherwise, it's probably just never worked.

**Comment by tractorcow** [comment]
It seems to work fine on the 3.3 branch. I guess it was fixed?

If you still notice the issue, please report exact versions that can be used to replicate this issue.

**Comment by patricknelson** [comment]
Yep, this is still happening for me in 3.3 and only in specific `GridField`'s. I have to head home now (since it's late) but it appears to be due to the grid field having a space in the name! This is another weird quirk that has croped up due to spaces being in the names of  some of my `GridField`'s. See https://github.com/silverstripe/silverstripe-framework/pull/5259 for context :sweat:

**Comment by patricknelson** [comment]
I've updated my instructions in the original post to reflect this so it can be reproduced. Let me know if you can reproduce the bug now!

**Comment by tractorcow** [comment]
I guess it wasn't as fixed as I had hoped, sorry.

**Comment by patricknelson** [comment]
Thanks for reopening @tractorcow I think I spent way more time than I should have trying to track this down (I am tenacious I guess).

**Comment by tractorcow** [comment]
See https://github.com/silverstripe/silverstripe-cms/issues/1506 for instance of this bug surfacing in media dialog.

**Comment by lukereative** [comment]
This appears to only be broken in 3.x, I cannot reproduce in 4.x – considering that 3.x is in security only support this issue is not going to be fixed for 3.x
