### ISSUE TITLE
Duplicate active indicators on tabs (underlines)

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#5270]
![image](https://cloud.githubusercontent.com/assets/936064/14239354/c90426c8-fa8e-11e5-924b-f0fbf486ce26.png)

Wrong indicators of tabs (the underlines): go to Security > Groups > click “Content Authors” > click “Permissions” tab > click “Groups” at the top of the page

Or go to `admin/security/groups/`

Going to `admin/security` and clicking groups doesn't change the URL.

Jira: https://silverstripe.atlassian.net/browse/OSS-1732

**Comment by clarkepaul** [comment]
I don't see this, maybe it has been fixed?

**Comment by tractorcow** [comment]
I've re-tested it with the above instructions. The issue is still there.

**Comment by tractorcow** [comment]
Both tabs have the active class.

![image](https://cloud.githubusercontent.com/assets/936064/15847772/af906816-2cdc-11e6-8502-625f026d10bf.png)

**Comment by dhensby** [comment]
I've experienced this too
