### ISSUE TITLE
React-based form action loading indicator doesn't animate in IE

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5283]
See `svg` rule in `admin/javascript/src/components/form-action/styles.scss`. Short story: SVG animation in IE sucks.

Will be merged in shortly to `master` via https://github.com/silverstripe/silverstripe-framework/pull/5278/

/cc @scott1702 @flashbackzoo

**Comment by tractorcow** [comment]
Is this fixed with #5278 now?

**Comment by chillu** [comment]
Sorry, my description was a bit misleading there: This problem is *caused* by new code I've merged in with #5278, rather than fixed through it. So it's not fixed yet. @scott1702 any chance you could have a look?

**Comment by scott1702** [comment]
Yep, it's at the top of my open-source todo list.

**Comment by clarkepaul** [comment]
Possibly replace with #7 http://tobiasahlin.com/spinkit/ but test in IE10 first.
