### ISSUE TITLE
UploadField not honoring default_max_file_size

### ISSUE THREAD

**Issue by p0lar-bear** [silverstripe/silverstripe-framework#6001]
Running SilverStripe 3.2 here, but the code for 3.4 seems to suggest the same should be happening. If I add a `default_max_file_size` entry to my config.yml, `UploadField` doesn't honor it.

```
Upload_Validator:
  default_max_file_size: 1g
```

I'm able to work around this by subclassing UploadField and giving it this ctor:

```
	public function __construct($name, $title = null, SS_List $items = null) {
		parent::__construct($name, $title, $items);
		
		$fileSize = Config::inst()->get('Upload_Validator', 'default_max_file_size');
		if (isset($fileSize)) {
			$this->getValidator()->setAllowedMaxFileSize($fileSize);
		}
	}
```

I think this logic should be rolled up into `UploadField`'s ctor.

**Comment by tractorcow** [comment]
It's fixed with https://github.com/silverstripe/silverstripe-framework/pull/5444 here, right, but not merged back to 3.2? Do you want to raise a PR to cherry pick this back?

**Comment by p0lar-bear** [comment]
I made the changes to my own Upload.php to test, but it didn't fix the problem.

What I'm seeing in the code is that `UploadField`'s constructor forces the validator to use the lower of PHP's `upload_max_filesize` or `post_max_size` values. It calls `UploadValidator::setAllowedExtensions` and passes in `File`'s `allowed_extensions` value, but then gets the INI values and calls `UploadValidator::setAllowedMaxFileSize` with that when it should probably check for this config first and then fall back to server settings.

i.e. this:
```
// get the lower max size
$maxUpload = File::ini2bytes(ini_get('upload_max_filesize'));
$maxPost = File::ini2bytes(ini_get('post_max_size'));
$this->getValidator()->setAllowedMaxFileSize(min($maxUpload, $maxPost));
```
...should be something like this:
```
// check config for size first
$fileSize = Config::inst()->get('Upload_Validator', 'default_max_file_size');
if (isset($fileSize)) {
        $this->getValidator()->setAllowedMaxFileSize($fileSize);
} else {
        // get the lower max size
        $maxUpload = File::ini2bytes(ini_get('upload_max_filesize'));
        $maxPost = File::ini2bytes(ini_get('post_max_size'));
        $this->getValidator()->setAllowedMaxFileSize(min($maxUpload, $maxPost));
}
```

**Comment by tractorcow** [comment]
How can you set a max file size that's larger than that allowed by the ini settings? It'll just fail at the php upload level, rather than at the validation stage.

**Comment by dhensby** [comment]
@tractorcow see the other related issue at #6000 - you can't associate a file that is larger than the max upload size even if it's already on the server

**Comment by p0lar-bear** [comment]
@tractorcow I agree that it doesn't make sense that a site admin should be able to specify a setting that simply won't work, however [the `UploadField` developer docs do warn about this, as well as suggest that the behavior I'm expecting but not getting should be happening](https://docs.silverstripe.org/en/3.2/developer_guides/forms/field_types/uploadfield/#limit-the-maximum-file-size).

Perhaps a way to address this would be to move the INI value setting to inside `Upload_Validator::setAllowedMaxFileSize()` as a fallback instead of having `UploadField` demand that it conform to the server settings?

What I'm seeing in my head while taking #6000 into account is, the method signature would be `(string|int|array $rules, bool $overrideServer=FALSE)`. If the rules don't exceed server settings, then the validator uses the supplied rules. If they exceed the server settings, but `$overrideServer` is set to `TRUE`, then the validator uses the supplied rules. If they exceed the server settings, and `$overrideServer` is either unsupplied or set to `FALSE`, then the validator dials back any rules that exceed the server maximums.

**Comment by tractorcow** [comment]
ok, so if you want to skip file size check for already uploaded files, you could do something like this in UploadField::validate couldn't you? 


```php
// Revalidate each file against nested validator
$this->upload->clearErrors();
foreach($files as $file) {
	// Generate $_FILES style file attribute array for upload validator
	$tmpFile = array(
		'name' => $file->Name,
		'type' => null, // Not used for type validation
		'size' => 0, // Skip file size check for already uploaded files
		'tmp_name' => null, // Should bypass is_uploaded_file check
		'error' => UPLOAD_ERR_OK,
	);
	$this->upload->validate($tmpFile);
}
```
