### ISSUE TITLE
Behat tests broken due to new modeladmin "owns" labels

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-framework#8029]
Now that all DataObjects have a polymorphic `has_many` files, `$owns` is universal, meaning every modeladmin, e.g. "Member" gets the versioned buttons ("Apply changes", "Publish", etc)

Relevant test failure: https://travis-ci.org/silverstripe/silverstripe-framework/jobs/369917097#L920

# PRs:

 - [x] https://github.com/silverstripe/silverstripe-versioned/pull/154
 - [X] https://github.com/silverstripe/silverstripe-admin/pull/523

**Comment by robbieaverill** [comment]
I fixed this in the behat steps: https://github.com/silverstripe/silverstripe-framework/pull/8058

**Comment by unclecheese** [comment]
This actually doesn't resolve the issue. I'm not sure @tractorcow 's assessment of the fix is accurate. The relevant tests failures were happening when editing, not creating. The appropriate fix, in my view, is to check that owned objects actually exist. `FileTracking` on a `Group`, for instance, is almost always empty, but just the definition of the ownership is enough to trigger the "Apply changes" button, which is a bad experience.

That said, the previous check for new records is also useful.

New PR: https://github.com/silverstripe/silverstripe-versioned/pull/154

**Comment by unclecheese** [comment]
Behat tests also broken due to new graphql schema loading in silverstripe/admin that was merged without a framework behat test.

Fix is here: https://github.com/silverstripe/silverstripe-admin/pull/523

**Comment by tractorcow** [comment]
Waiting until https://github.com/silverstripe/silverstripe-versioned/pull/154 is merged
