### ISSUE TITLE
TreeDropdownField fails to parse value (4.7.0+)

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-framework#9880]
## Affected Versions

4.7.0
4.7.1
4.7.2
4.7.3

## Description

After upgrading from 4.6.1 to 4.7.1, I discovered that `TreeDropdownField` and `TreeMultiselectField` would often fail to load their previous value, resulting in their value being wiped when the record was next saved.

**This would only occur in certain environments. e.g. on the live site hosting in a cPanel account, but not on my local MAMP environment.**

This was most apparent in the Page Settings > Parent page & Viewer Groups fields, but also affects the page field on a `RedirectorPage`.

The issue seems to be that in certain environments (I've been unable to identify which or why), when the JSON in the `data-state` attribute for the field is generated it adds quotes around integers. e.g. `"value":"656"` vs `"value":656`.

Since Silverstripe 4.7.0, this seems to cause the field to fail to parse the value (ID). 
In 4.6.1 and below, it can read the value fine, with or without the quote marks.

Can we identify what changed in 4.7.0 that broke this?

## Steps to Reproduce

With a 4.7.x site hosted in an effected environment (possibly any cPanel host):
1. Go to any Page Settings
2. Set **Who can view this page?**: Only these groups (choose from list)
3. Select a group from the **Viewer Groups** dropdown.
4. Click Save/Publish

### What happens?
The page reloads and the **Viewer Groups** field is empty.

### What I expect to happen.
The page to reload, and the **Viewer Groups** field to be populated with the group previously selected above.

---

Also see forum post: https://forum.silverstripe.org/t/page-settings-dropdowns-not-populating-on-4-7-1/3852/

### PRs
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10009

**Comment by maxime-rainville** [comment]
Can you tell us what version of PHP you are using on your dev and production environments.

I'm thinking it could also be a DB issue if one database return the number as an numeric while the other one returns the value as a string.

**Comment by purplespider** [comment]
I should have mentioned, PHP 7.4.9 on dev and 7.4.14 on production. Tried different PHP versions on production with no change.

I too initially wondered if it was related to the database collation changes in 4.7.0, but when I pointed my dev install at the production database, the issue still didn't occur.

While I am curious about what is causing the differences in JSON generation behaviour, this issue does appear to have been caused by a change related to JSON parsing in 4.7.0.

**Comment by purplespider** [comment]
Spent the day on this as it was blocking me from updating my sites to 4.7 and believe I have finally managed to get to the bottom of it. It turns out the issue was incorrect PHP modules on the production server for the Silverstripe MySQL connector I was using.

I had been using this setup for my sites:

`SS_DATABASE_CLASS="MySQLPDODatabase"`
With PHP Modules:
`mysqli mysqlnd`

But it turns out, when using `MySQLPDODatabase`, I should have the following PHP modules enabled instead:
`nd_mysqli nd_pdo_mysql`

This fixes the issue instantly.

I discovered this when I tried changing `SS_DATABASE_CLASS` from `MySQLPDODatabase` to `MySQLDatabase` (dropping the `PDO`, and received this message with a dev/build:

> ERROR [User Notice]: mysqlnd PHP library is not available, numeric values will be fetched from the DB as strings

So while it seems that something was changed in 4.7.0 which causes Silverstripe to fail to read numbers from strings in JSON, this explains where the extra quotes were coming from in the first place.

@maxime-rainville Now that we know the correct fix is on the server setup, do you still feel that Silverstripe should have been able to handle this? If not, perhaps we should look at adding a similar check-in `PDOConnector` that there already is in `MySQLiConnector` to flag when that `numeric values will be fetched from the DB as strings`.

**Comment by xini** [comment]
I have this same issue on several environments. 

Shouldn't the database layer of SS take care of casting numeric values correctly? With the database connector we have an abstraction that should take care of any weird database behavior, no?

**Comment by xini** [comment]
This goes into the same category of issues as https://github.com/silverstripe/silverstripe-framework/issues/9809.

**Comment by maxime-rainville** [comment]
I still think we should aim to make sure it works either way. But the fact that the issue is at least partially attributable to a misconfiguration warrants downgrading this to `impact/medium`.

**Comment by xini** [comment]
Then what exactly is your suggested solution, @maxime-rainville? I am running MySQLDatabase with mysqlnd and still have the issue.  This is the default/recommended config for SS, no?

**Comment by Tijsje** [comment]
https://github.com/silverstripe/silverstripe-framework/blob/4/src/Forms/TreeDropdownField.php#L555

Change to  ->setBody(json_encode($json, JSON_NUMERIC_CHECK)); an option?

**Comment by emteknetnz** [comment]
PR https://github.com/silverstripe/silverstripe-framework/pull/10009

**Comment by emteknetnz** [comment]
While, I wasn't able to directly replicate the issue as reported as I have a fairly standard database setup, we've merged a [fix](https://github.com/silverstripe/silverstripe-framework/pull/10009) to cast `DBInt::getValue()` as an `(int)`

I'm going to close this issue with the assumption that this will fix the issue

@purplespider @xini if you're able to test with by updating your composer with something like `"silverstripe/framework": "4.8.x-dev as 4.7.0"` then that would be appreciated.  Please reply on this issue to let us know if this resolved it for you.

If you find any problems, please ping me direct on this issue and I'll re-open it for you and investigate further

**Comment by xini** [comment]
This has been resolved for me with 4.8.0. Thanks.

**Comment by emteknetnz** [comment]
@xini Was that resolved by upgrading to 4.8.0, or by implementing the code fix that was just merged into 4.8.x-dev ?

**Comment by xini** [comment]
@emteknetnz 4.8.0 was enough for me. Not sure why...

**Comment by purplespider** [comment]
@emteknetnz Thank you!

I just reproduced the issue in `4.7.3` again to be sure, upgraded to `4.8.0@stable` and it was still broken, but upon using `4.8.x-dev as 4.7.0` I can confirm it works as expected!
